### ISSUE TITLE
It's Not Initializing

### ISSUE THREAD

**Issue by vamsikreddys** [PavanReddy77/SeleniumWebDriver_3#1]
package Locators;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class Loginpage {
	
	public static  WebDriver driver;
	
	@FindBy(id="identifierId")
    static WebElement username;

    @FindBy(name="password")
    static WebElement password;    

    @FindBy(xpath="//span[contains(text(),'Next')]")
    static WebElement next1;

    @FindBy(xpath="//*[@id=\"passwordNext\"]/span/span")
    static WebElement next2;
    
    public static void PageFactory() {
    	PageFactory.initElements(driver, driver);
		// TODO Auto-generated method stub

	}
    
    @Test
    public static void  log() {
    	username.sendKeys("vamsi");
    	
    }
	
	@BeforeTest
		public void beforeTest() {
		  System.setProperty("webdriver.chrome.driver","D:\\selenim\\chromedriver.exe");
			  driver = new ChromeDriver();
			  driver.get("http://www.gmail.com/");
			  //driver.manage().deleteAllCookies();
			  driver.manage().window().maximize();
	}
	
	
}

**Comment by PavanReddy77** [comment]
Please do refer below to achieve POM Design Pattern. 

https://github.com/PavanReddy77/MavenHybridFramework
